
import java.awt.event.ActionListener;


public class studView extends javax.swing.JFrame {
    
    public studView() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtSECT = new javax.swing.JTextField();
        txtSUB = new javax.swing.JTextField();
        txtINS = new javax.swing.JTextField();
        txtNAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT RECORD MANAGEMENT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 440, 60);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(30, 390, 72, 23);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(130, 390, 90, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(340, 390, 90, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(240, 390, 80, 23);

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay);
        btnDisplay.setBounds(450, 390, 90, 23);
        getContentPane().add(txtID);
        txtID.setBounds(110, 110, 140, 22);
        getContentPane().add(txtSECT);
        txtSECT.setBounds(110, 210, 140, 22);
        getContentPane().add(txtSUB);
        txtSUB.setBounds(410, 130, 140, 22);

        txtINS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtINSActionPerformed(evt);
            }
        });
        getContentPane().add(txtINS);
        txtINS.setBounds(410, 190, 140, 22);
        getContentPane().add(txtNAME);
        txtNAME.setBounds(110, 160, 140, 22);

        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 100, 16);

        jLabel3.setText("Student Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(7, 160, 100, 16);

        jLabel4.setText("Student Section:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(7, 210, 100, 16);

        jLabel5.setText("Student Subject:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 130, 120, 20);

        jLabel6.setText("Instructor:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 190, 100, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Section", "Subject", "Instructor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 260, 400, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtINSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtINSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtINSActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisplayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnDisplay;
    public javax.swing.JButton btnSearch;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtINS;
    public javax.swing.JTextField txtNAME;
    public javax.swing.JTextField txtSECT;
    public javax.swing.JTextField txtSUB;
    // End of variables declaration//GEN-END:variables

    public void allListener(ActionListener listenForButton) {
        btnAdd.addActionListener(listenForButton);
        btnDelete.addActionListener(listenForButton);
        btnUpdate.addActionListener(listenForButton);
        btnSearch.addActionListener(listenForButton);
        btnDisplay.addActionListener(listenForButton);
    }

    void clearFields() {
        txtID.setText("");
        txtINS.setText("");
        txtNAME.setText("");
        txtSECT.setText("");
        txtSUB.setText("");
    }
}
